name: TESTS

jobs:
  test:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14.18
    - run: npm test
  falaOlaMundo:
    - run: echo 'olá mundo'
  build:
    - run: docker build -t talk-todo-list-api:latest .