name: TEST-AND-BUILD-IMAGE
runs-on: ubuntu-latest

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.18
      - run: npm test
  falaOlaMundo:
    steps:
      - run: echo 'olá mundo'
  build:
    steps:
      - run: docker build -t talk-todo-list-api:latest .